theme = "ayu_evolve"

[editor]
true-color = true
line-number = "relative"
mouse = false
color-modes = true
auto-pairs = true
gutters = ["diff", "line-numbers"]
bufferline = "never"

[editor.statusline]
right = ["diagnostics", "selections", "register", "position", "file-encoding", "version-control"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = false

[keys.normal.space]
e = ":sh zellij run -fc -- yazi"

