theme = "kanagawa"

[editor]
true-color = true
line-number = "relative"
mouse = false
color-modes = true
auto-pairs = true
gutters = ["diff", "line-numbers"]
bufferline = "never"

[editor.statusline]
right = ["diagnostics", "selections", "register", "position", "file-encoding", "version-control"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

# [editor.auto-save]
# after-delay.enable = true
# after-delay.timeout = 1000


[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = false

[keys.normal]
C-l = ["move_prev_word_start", "move_next_word_end", "search_selection", "select_all", "select_regex"]

[keys.normal.space]
e = ":sh zellij run -fc -- yazi"

