[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff-lsp"

[language-server.ruff.config.settings]
args = ["--ignore", "E501"]

[language.formatter]
command = "black"
args = ["--line-length", "88", "--quiet", "-"]


[[language]]
name = "markdown"
language-servers = [ "marksman" ]


[[language]]
name = "latex"
language-servers = ["texlab", "ltex-ls"]

[language-server.texlab.config.texlab.build]
args = ["-shell-escape", "-pdf", "-interaction=nonstopmode", "-synctex=1", "%f"]
onSave = true
forwardSearchAfter = true
# executable = "tectonic"
# args = [
#  "-X",
#  "compile",
#  "%f",
#  "--synctex",
#  "--keep-logs",
#  "--keep-intermediates",
#  "--outdir=build",
#  "-Zshell-escape",
#  ]

[language-server.texlab.config.texlab.forwardSearch]
executable = "sioyek"
args = [
    "--reuse-window",
    "--execute-command",
    "toggle_synctex",
    "--inverse-search",
    "texlab inverse-search -i \"%%1\" -l %%2",
    "--forward-search-file",
    "%f",
    "--forward-search-line",
    "%l",
    "%p",  
]

[language-server.texlab.config.texlab.chktex]
onEdit = true
